name: Build and Deploy Python App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  AZURE_WEBAPP_NAME: 'python-fastapi-json' # Set this to your app name
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create venv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r require_py/requirements.txt

      # Optional: Run tests here
      # - name: Run Tests
      #   run: |
      #     source venv/bin/activate
      #     pytest

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .  # Uploads the entire root directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}